### ISSUE TITLE
Heartbeat article

### ISSUE THREAD

**Issue by michelleyho** [ashishps1/awesome-system-design-resources#11]
Trying to read the heartbeat article at this [link](https://martinfowler.com/articles/patterns-of-distributed-systems/heartbeat.html).

Article seems extremely short and at end of page it mentions read chapter 7 of online book.  Is this intentional? Not all folks have free access to online oreilly books.

Is there some other article you recommend for "heartbeat"... or is it just that simple to be described in a few sentences?

**Comment by ashishps1** [comment]
Hi @michelleyho ,

The concept behind heartbeats is simple.

I couldn't find a good detailed article online that's why added this one.

I was planning to write a article about heartbeats myself on my blog (https://newsletter.ashishps.com/)

Since you pointed it out, I will prioritize it and try to publish it by tomorrow.

**Comment by michelleyho** [comment]
Thanks @ashishps1! I was thinking it was simple, but I wasn't positive.  I quite like the other articles that you've written so far in your newsletter! Looking forward to reading more of them!

**Comment by ashishps1** [comment]
@michelleyho I just published the article on HeartBeats: https://newsletter.ashishps.com/p/heartbeats-in-distributed-systems
Hope you find it useful.

Closing this issue!

**Comment by michelleyho** [comment]
@ashishps1 Great article like always! Thank you! Looking forward to your articles for all the other topics!
